project_id = "obijcwprhqyslfplnego"

[functions.delete-account]
verify_jwt = false

[functions.admin-moderate]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.security-scan-monitor]
verify_jwt = false


