// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-rooms.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_rooms_default = defineTool({
  name: "list_rooms",
  title: "List rooms",
  description: "List all confession rooms (topics) available on Conffo.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await anonClient().from("rooms").select("id, name, description, is_pinned").order("is_pinned", { ascending: false }).order("name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rooms: data }
    };
  }
});

// src/lib/mcp/tools/search-confessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_confessions_default = defineTool2({
  name: "search_confessions",
  title: "Search confessions",
  description: "Search recent public anonymous confessions on Conffo. Optionally filter by room ID or match text content.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text substring to match in confession content."),
    roomId: z.string().trim().optional().describe("Room ID to filter by (e.g. 'relationships', 'work')."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of confessions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, roomId, limit }) => {
    let q = anonClient2().from("confessions").select("id, content, room_id, created_at, tags, media_type").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (roomId) q = q.eq("room_id", roomId);
    if (query) q = q.ilike("content", `%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { confessions: data }
    };
  }
});

// src/lib/mcp/tools/get-confession.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_confession_default = defineTool3({
  name: "get_confession",
  title: "Get confession",
  description: "Fetch a single confession by its ID, including comments count and reactions.",
  inputSchema: {
    id: z2.string().uuid().describe("Confession UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const client = anonClient3();
    const { data: confession, error } = await client.from("confessions").select("id, content, room_id, created_at, tags, media_type, media_url").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!confession) {
      return { content: [{ type: "text", text: "Confession not found." }], isError: true };
    }
    const { data: comments } = await client.from("comments").select("id, content, created_at").eq("confession_id", id).order("created_at", { ascending: true }).limit(50);
    return {
      content: [{ type: "text", text: JSON.stringify({ confession, comments }) }],
      structuredContent: { confession, comments: comments ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trending-confessions.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function anonClient4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_trending_confessions_default = defineTool4({
  name: "get_trending_confessions",
  title: "Get trending confessions",
  description: "Return the most-reacted-to confessions from the last N hours, optionally filtered by room. Ranked by total reactions.",
  inputSchema: {
    roomId: z3.string().trim().optional().describe("Room ID to filter by (e.g. 'relationships')."),
    hours: z3.number().int().min(1).max(720).optional().describe("Lookback window in hours (default 48)."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max confessions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ roomId, hours, limit }) => {
    const client = anonClient4();
    const sinceISO = new Date(Date.now() - (hours ?? 48) * 36e5).toISOString();
    const max = limit ?? 10;
    let cq = client.from("confessions").select("id, content, room_id, created_at, tags, media_type").gte("created_at", sinceISO);
    if (roomId) cq = cq.eq("room_id", roomId);
    const { data: confessions, error } = await cq.limit(500);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!confessions?.length) {
      return {
        content: [{ type: "text", text: "[]" }],
        structuredContent: { trending: [] }
      };
    }
    const ids = confessions.map((c) => c.id);
    const { data: reactions } = await client.from("reactions").select("confession_id").in("confession_id", ids);
    const counts = /* @__PURE__ */ new Map();
    for (const r of reactions ?? []) {
      counts.set(r.confession_id, (counts.get(r.confession_id) ?? 0) + 1);
    }
    const ranked = confessions.map((c) => ({ ...c, reaction_count: counts.get(c.id) ?? 0 })).sort((a, b) => b.reaction_count - a.reaction_count).slice(0, max);
    return {
      content: [{ type: "text", text: JSON.stringify(ranked) }],
      structuredContent: { trending: ranked, window_hours: hours ?? 48 }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "conffo-mcp",
  title: "Conffo",
  version: "0.2.0",
  instructions: "Read-only access to public anonymous confessions on Conffo. All tools are read-only by design; writing confessions/reactions/comments and admin moderation require OAuth (not yet enabled). Use `list_rooms` to discover topics, `search_confessions` to browse or filter, `get_confession` for a single item with comments, and `get_trending_confessions` to rank by reactions within a lookback window.",
  tools: [
    list_rooms_default,
    search_confessions_default,
    get_confession_default,
    get_trending_confessions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
